# Generated by Django 4.1.5 on 2023-01-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_event_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='address',
            new_name='localAddress',
        ),
        migrations.AddField(
            model_name='event',
            name='district',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='municipality',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
